DBNAME = "translate.db"
TESTNAME = "test"
DBDIR = "DB"
TRANSLATEDIR = "Translate"
STATSDIR = "Stats"
DICTDIR = "Dict"
TIMEFORMAT = "%Y-%m-%d_%H-%M-%S"
LINGVO_URL = 'http://www.lingvo-online.ru/en/Search?searchMode=Examples&searchSrcLang=en&searchDestLang=ru&searchText=%s'
PASSED_LIMIT = 1
EXAMPLES_LIFETIME = 300
